version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: duacoder-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: duacoder_db
      MYSQL_USER: duacoder
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysqls
    networks:
      - duacoder-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: node:20.11
    container_name: myapp
    working_dir: /app
    volumes:
      - ../:/app  
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: duacoder_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - duacoder-network
    command: sh -c "npm install && npm run migration:run && npm run start:dev"
    ports:
      - "3000:3000"

networks:
  duacoder-network:
    driver: bridge
