version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: duacoder-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: duacoder_db
      MYSQL_USER: duacoder
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysqls
    networks:
      - duacoder-network

networks:
  duacoder-network:
    driver: bridge
